version: '3.0'
services:
   mymongodb1:
     container_name: mymongodb1
     build:
       context: .
       dockerfile: Dockerfile-mongodb
     image: mymongodb:1.0.0
     ports:
       - "27017:27017"
     restart: always

   myapp1:
     container_name: myapp1
     build:
       context: .
       dockerfile: Dockerfile-app
     image: myapp:1.0.0
     links:
       - mymongodb1:mymongodb1
